# Generated by Django 4.2.16 on 2024-11-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_alter_project_name_alter_project_project_dis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('is_exits', models.BooleanField(default=True)),
            ],
        ),
    ]
